#!/bin/bash
for v in "$@" ; do
	if [[ ! -d $v ]];  then
		echo "minfile: $v: not a directory." >&2
		
	else
		for fichier in $v/* ; do 
				
			fichier=$( basename "$fichier" )

			if [[ ! $fichier =~ [[:lower:]]{1,} ]] ; then 
				
				mv "$v/$fichier" "$v/${fichier,,}"
			fi

		done
	fi
done
